### PR TITLE
Update Command component in DeveloperGuide

### PR DESCRIPTION
**Pull request by Zeno-Zr**
* Reduce the details written in command component

### CODE REVIEW

**Review by Stella1585 — COMMENTED** [review]
hm y are my lines for deadline under yours too

**Comment by darrenangwx** [comment]
> hm y are my lines for deadline under yours too

There needs to be linebreaks between lines 96 and 97, and lines 121 and 122. @Zeno-Zr can you add those line breaks before we merge this? thank you

**Comment by Zeno-Zr** [comment]
> hm y are my lines for deadline under yours too

can you indicate where in the document are your lines under mine? I can't seem to find it on my end.

**Review by darrenangwx — APPROVED** [review]
looks good to me

**Pull request merged**
